; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
upload_speed = 115200
monitor_speed = 115200
test_speed = 115200

lib_extra_dirs=V:/Work/Projects/Arduino/embo
lib_deps = 
    shared
    composer
    NTPClient
    adafruit/RTClib             # for RTC module
    adafruit/Adafruit BusIO     # for I2C communication
	adafruit/Adafruit NeoPixel  # for status LED
    bblanchon/ArduinoJson       # for parsing weather API responses
    lovyan03/LovyanGFX          # for display handling
    Wire

lib_ldf_mode = deep+

#upload_protocol = esptool

[env:prod_release]
build_type = debug

platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- UPLOAD via Serial (UART cable) ---
upload_protocol = esptool
upload_port = COM16      ; Use your stable CH343 port
upload_speed = 921600   ; High speed works fine for UART

monitor_port = COM16
test_port = COM16
monitor_dtr = 0
monitor_rts = 0

; Force standard Flash and disable PSRAM for the bare board
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi

build_flags = 
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0  ; Routes Serial to Native USB port

; debugger configuration
debug_load_mode = manual
debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_speed = 5000
debug_extra_cmds =
    set remotetimeout 30
    monitor reset halt

[env:proto_release]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_type = release
test_build_src = yes
build_unflags = -Os
build_flags = -O2 -g

upload_port = COM11
UPLOAD_SPEED = 921600
test_port = COM11
monitor_port = COM11
monitor_speed = 115200
monitor_dtr = 1
monitor_rts = 1

[env:proto_debug]
platform = espressif32
board = freenove_esp32_s3_wroom
framework = arduino
build_type = debug
build_flags = -Og -ggdb3 -g3

upload_port = COM11
monitor_port = COM11
monitor_speed = 115200
test_port = COM11
test_speed = 115200

#pio test -e debug --without-uploading --without-testing
#pio debug -e debug
